package br.com.pokedex.dataService

import br.com.pokedex.domain.Pokemon
import br.com.pokedex.domain.PokemonInstance
import br.com.pokedex.domain.Type
import br.com.pokedex.exceptions.PokemonNotFoundException
import org.springframework.stereotype.Service
import javax.annotation.PostConstruct

@Service
class PokemonFactory {

    @PostConstruct
    fun init() {
        fillList()
    }

    private var pokemons: MutableList<Pokemon> = mutableListOf()

    fun get(name: String): Pokemon {
        pokemons.find { it.name.equals(name, ignoreCase = false) }?.let {
            return it
        }

        throw PokemonNotFoundException("Pokemon Not found")
    }

    fun all(): List<Pokemon> {
        return this.pokemons
    }

    fun getInstance(name: String): PokemonInstance {
        return PokemonInstance(pokemon = get(name))
    }

    private fun fillList() {
//            Primeira geração
        pokemons.add(Pokemon(name = "Missingno", types = listOf(Type.NORMAL, Type.FLYING)))
        pokemons.add(Pokemon(name = "Bulbasaur", types = listOf(Type.GRASS, Type.POISON)))
        pokemons.add(Pokemon(name = "Ivysaur", types = listOf(Type.GRASS, Type.POISON)))
        pokemons.add(Pokemon(name = "Venusaur", types = listOf(Type.GRASS, Type.POISON)))
        pokemons.add(Pokemon(name = "Charmander", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Charmeleon", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Charizard", types = listOf(Type.FIRE, Type.FLYING)))
        pokemons.add(Pokemon(name = "Squirtle", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Wartortle", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Blastoise", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Caterpie", types = listOf(Type.BUG)))
        pokemons.add(Pokemon(name = "Metapod", types = listOf(Type.BUG)))
        pokemons.add(Pokemon(name = "Butterfree", types = listOf(Type.BUG, Type.FLYING)))
        pokemons.add(Pokemon(name = "Weedle", types = listOf(Type.BUG, Type.POISON)))
        pokemons.add(Pokemon(name = "Kakuna", types = listOf(Type.BUG, Type.POISON)))
        pokemons.add(Pokemon(name = "Beedrill", types = listOf(Type.BUG, Type.POISON)))
        pokemons.add(Pokemon(name = "Pidgey", types = listOf(Type.NORMAL, Type.FLYING)))
        pokemons.add(Pokemon(name = "Pidgeotto", types = listOf(Type.NORMAL, Type.FLYING)))
        pokemons.add(Pokemon(name = "Pidgeot", types = listOf(Type.NORMAL, Type.FLYING)))
        pokemons.add(Pokemon(name = "Rattata", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Raticate ", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Spearow", types = listOf(Type.NORMAL, Type.FLYING)))
        pokemons.add(Pokemon(name = "Fearow", types = listOf(Type.NORMAL, Type.FLYING)))
        pokemons.add(Pokemon(name = "Ekans", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Arbok", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Pikachu", types = listOf(Type.ELETRICITY)))
        pokemons.add(Pokemon(name = "Raichu", types = listOf(Type.ELETRICITY)))
        pokemons.add(Pokemon(name = "Sandshrew", types = listOf(Type.GROUND)))
        pokemons.add(Pokemon(name = "Sandslash", types = listOf(Type.GROUND)))
        pokemons.add(Pokemon(name = "Nidoran Fêmea", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Nidorina", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Nidoqueen", types = listOf(Type.POISON, Type.GROUND)))
        pokemons.add(Pokemon(name = "Nidoran Macho", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Nidorino", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Nidoking", types = listOf(Type.POISON, Type.GROUND)))
        pokemons.add(Pokemon(name = "Clefairy", types = listOf(Type.FAIRY)))
        pokemons.add(Pokemon(name = "Clefable", types = listOf(Type.FAIRY)))
        pokemons.add(Pokemon(name = "Vulpix", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Ninetales", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Jigglypuff", types = listOf(Type.FAIRY, Type.NORMAL)))
        pokemons.add(Pokemon(name = "Wigglytuff", types = listOf(Type.FAIRY, Type.NORMAL)))
        pokemons.add(Pokemon(name = "Zubat", types = listOf(Type.POISON, Type.FLYING)))
        pokemons.add(Pokemon(name = "Golbat", types = listOf(Type.POISON, Type.FLYING)))
        pokemons.add(Pokemon(name = "Oddish", types = listOf(Type.GRASS, Type.POISON)))
        pokemons.add(Pokemon(name = "Gloom", types = listOf(Type.GRASS, Type.POISON)))
        pokemons.add(Pokemon(name = "Vileplume", types = listOf(Type.GRASS, Type.POISON)))
        pokemons.add(Pokemon(name = "Paras", types = listOf(Type.GRASS, Type.BUG)))
        pokemons.add(Pokemon(name = "Parasect", types = listOf(Type.GRASS, Type.BUG)))
        pokemons.add(Pokemon(name = "Venonat", types = listOf(Type.BUG, Type.POISON)))
        pokemons.add(Pokemon(name = "Venomoth", types = listOf(Type.BUG, Type.POISON)))
        pokemons.add(Pokemon(name = "Diglett", types = listOf(Type.GROUND)))
        pokemons.add(Pokemon(name = "Dugtrio", types = listOf(Type.GROUND)))
        pokemons.add(Pokemon(name = "Meowth", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Persian", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Psyduck", types = listOf(Type.WATER, Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Golduck", types = listOf(Type.WATER, Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Mankey", types = listOf(Type.FIGHT)))
        pokemons.add(Pokemon(name = "Primeape", types = listOf(Type.FIGHT)))
        pokemons.add(Pokemon(name = "Growlithe", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Arcanine", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Poliwag", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Poliwhirl", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Poliwrath", types = listOf(Type.WATER, Type.FIGHT)))
        pokemons.add(Pokemon(name = "Abra", types = listOf(Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Kadabra", types = listOf(Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Alakazam", types = listOf(Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Machop", types = listOf(Type.FIGHT)))
        pokemons.add(Pokemon(name = "Machoke", types = listOf(Type.FIGHT)))
        pokemons.add(Pokemon(name = "Machamp", types = listOf(Type.FIGHT)))
        pokemons.add(Pokemon(name = "Bellsprout", types = listOf(Type.GRASS, Type.POISON)))
        pokemons.add(Pokemon(name = "Weepinbell", types = listOf(Type.GRASS, Type.POISON)))
        pokemons.add(Pokemon(name = "Victreebel", types = listOf(Type.GRASS, Type.POISON)))
        pokemons.add(Pokemon(name = "Tentacool", types = listOf(Type.WATER, Type.POISON)))
        pokemons.add(Pokemon(name = "Tentacruel", types = listOf(Type.WATER, Type.POISON)))
        pokemons.add(Pokemon(name = "Geodude", types = listOf(Type.ROCK, Type.GROUND)))
        pokemons.add(Pokemon(name = "Graveler", types = listOf(Type.ROCK, Type.GROUND)))
        pokemons.add(Pokemon(name = "Golem", types = listOf(Type.ROCK, Type.GROUND)))
        pokemons.add(Pokemon(name = "Ponyta", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Rapidash", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Slowpoke", types = listOf(Type.WATER, Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Slowbro", types = listOf(Type.WATER, Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Magnemite", types = listOf(Type.ELETRICITY, Type.STEEL)))
        pokemons.add(Pokemon(name = "Magneton", types = listOf(Type.ELETRICITY, Type.STEEL)))
        pokemons.add(Pokemon(name = "Farfetch'd", types = listOf(Type.NORMAL, Type.FLYING)))
        pokemons.add(Pokemon(name = "Doduo", types = listOf(Type.NORMAL, Type.FLYING)))
        pokemons.add(Pokemon(name = "Dodrio", types = listOf(Type.NORMAL, Type.FLYING)))
        pokemons.add(Pokemon(name = "Seel", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Dewgong", types = listOf(Type.WATER, Type.ICE)))
        pokemons.add(Pokemon(name = "Grimer", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Muk", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Shellder", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Cloyster", types = listOf(Type.WATER, Type.ICE)))
        pokemons.add(Pokemon(name = "Gastly", types = listOf(Type.GROUND, Type.POISON)))
        pokemons.add(Pokemon(name = "Haunter", types = listOf(Type.GROUND, Type.POISON)))
        pokemons.add(Pokemon(name = "Gengar", types = listOf(Type.GROUND, Type.POISON)))
        pokemons.add(Pokemon(name = "Onix", types = listOf(Type.ROCK, Type.GROUND)))
        pokemons.add(Pokemon(name = "Drowzee", types = listOf(Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Hypno", types = listOf(Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Krabby", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Kingler", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Voltorb", types = listOf(Type.ELETRICITY)))
        pokemons.add(Pokemon(name = "Electrode", types = listOf(Type.ELETRICITY)))
        pokemons.add(Pokemon(name = "Exeggcute", types = listOf(Type.GRASS, Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Exeggutor", types = listOf(Type.GRASS, Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Cubone", types = listOf(Type.GROUND)))
        pokemons.add(Pokemon(name = "Marowak", types = listOf(Type.GROUND)))
        pokemons.add(Pokemon(name = "Hitmonlee", types = listOf(Type.FIGHT)))
        pokemons.add(Pokemon(name = "Hitmonchan", types = listOf(Type.FIGHT)))
        pokemons.add(Pokemon(name = "Lickitung", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Koffing", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Weezing", types = listOf(Type.POISON)))
        pokemons.add(Pokemon(name = "Rhyhorn", types = listOf(Type.GROUND, Type.ROCK)))
        pokemons.add(Pokemon(name = "Rhydon", types = listOf(Type.GROUND, Type.ROCK)))
        pokemons.add(Pokemon(name = "Chansey", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Tangela", types = listOf(Type.GRASS)))
        pokemons.add(Pokemon(name = "Kangaskhan", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Horsea", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Seadra", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Goldeen", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Seaking", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Staryu", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Starmie", types = listOf(Type.WATER, Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Mr.Mime", types = listOf(Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Scyther", types = listOf(Type.BUG, Type.FLYING)))
        pokemons.add(Pokemon(name = "Jynx", types = listOf(Type.ICE, Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Electabuzz", types = listOf(Type.ELETRICITY)))
        pokemons.add(Pokemon(name = "Magmar", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Pinsir", types = listOf(Type.BUG)))
        pokemons.add(Pokemon(name = "Tauros", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Magikarp", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Gyarados", types = listOf(Type.WATER, Type.FLYING)))
        pokemons.add(Pokemon(name = "Lapras", types = listOf(Type.WATER, Type.ICE)))
        pokemons.add(Pokemon(name = "Ditto", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Eevee", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Vaporeon", types = listOf(Type.WATER)))
        pokemons.add(Pokemon(name = "Jolteon", types = listOf(Type.ELETRICITY)))
        pokemons.add(Pokemon(name = "Flareon", types = listOf(Type.FIRE)))
        pokemons.add(Pokemon(name = "Porygon", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Omanyte", types = listOf(Type.ROCK, Type.WATER)))
        pokemons.add(Pokemon(name = "Omastar", types = listOf(Type.ROCK, Type.WATER)))
        pokemons.add(Pokemon(name = "Kabuto", types = listOf(Type.ROCK, Type.WATER)))
        pokemons.add(Pokemon(name = "Kabutops", types = listOf(Type.ROCK, Type.WATER)))
        pokemons.add(Pokemon(name = "Aerodactyl", types = listOf(Type.ROCK, Type.WATER)))
        pokemons.add(Pokemon(name = "Snorlax", types = listOf(Type.NORMAL)))
        pokemons.add(Pokemon(name = "Articuno", types = listOf(Type.ICE, Type.FLYING)))
        pokemons.add(Pokemon(name = "Zapdos", types = listOf(Type.ELETRICITY, Type.FLYING)))
        pokemons.add(Pokemon(name = "Moltres", types = listOf(Type.FIRE, Type.FLYING)))
        pokemons.add(Pokemon(name = "Dratini", types = listOf(Type.DRAGON)))
        pokemons.add(Pokemon(name = "Dragonair", types = listOf(Type.DRAGON)))
        pokemons.add(Pokemon(name = "Dragonite", types = listOf(Type.DRAGON, Type.FLYING)))
        pokemons.add(Pokemon(name = "Mewtwo", types = listOf(Type.PSYCHIC)))
        pokemons.add(Pokemon(name = "Mew", types = listOf(Type.PSYCHIC)))
    }

}
